AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Amplify Frontend for Centralized Delivery Platform'

Parameters:
  AppName:
    Type: String
    Default: 'centralized-delivery-platform-frontend'
    Description: 'Name of the Amplify application'
  
  EnvironmentName:
    Type: String
    Default: 'production'
    Description: 'Environment name'

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Description: 'Centralized Delivery Platform Frontend - Static hosting with Lambda backend'
      Platform: WEB
      Repository: 'https://github.com/your-username/centralized-platform'
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - echo "🚀 Preparing Centralized Delivery Platform for AWS Amplify"
                - echo "📁 Setting up static files..."
                - cd fastapi-template/static
            build:
              commands:
                - echo "🔧 Configuring frontend for production deployment"
                - echo "🔗 Backend: https://l17hfioxt7.execute-api.eu-north-1.amazonaws.com/api/"
                - echo "✅ Frontend ready for deployment"
          artifacts:
            baseDirectory: fastapi-template/static
            files:
              - '**/*'
      CustomRules:
        - Source: '/<*>'
          Target: '/index.html'
          Status: '200'
        - Source: '/login'
          Target: '/login.html'
          Status: '200'
        - Source: '/dashboard'
          Target: '/index.html'
          Status: '200'
      EnvironmentVariables:
        - Name: 'API_BASE_URL'
          Value: 'https://l17hfioxt7.execute-api.eu-north-1.amazonaws.com/api/'
        - Name: 'ENVIRONMENT'
          Value: 'production'

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: 'main'
      Description: 'Production branch for Centralized Delivery Platform'
      EnableAutoBuild: true
      EnablePerformanceMode: true
      Framework: 'Web'
      Stage: 'PRODUCTION'

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Sub '${AppName}.amplifyapp.com'
      EnableAutoSubDomain: true
      SubDomainSettings:
        - BranchName: !GetAtt AmplifyBranch.BranchName
          Prefix: 'www'

Outputs:
  AmplifyAppId:
    Description: 'Amplify App ID'
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyAppURL:
    Description: 'Amplify App URL'
    Value: !Sub 'https://main.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppURL'

  BackendAPI:
    Description: 'Backend API URL'
    Value: 'https://l17hfioxt7.execute-api.eu-north-1.amazonaws.com/api/'
    Export:
      Name: !Sub '${AWS::StackName}-BackendAPI'
