#!/bin/bash
echo "🚀 Simple deployment without AWS CLI"
echo "📋 Options:"
echo ""
echo "1. 🌐 AWS Amplify Console (Recommended):"
echo "   • Go to: https://console.aws.amazon.com/amplify/"
echo "   • Click 'Create App' → 'Host web app'"
echo "   • Connect GitHub: ghaythalijarad/entralized-delivery-platform"
echo "   • Amplify will auto-detect the Dockerfile and deploy"
echo ""
echo "2. 🔑 Or fix AWS credentials:"
echo "   • AWS Console → IAM → Users → Security credentials"
echo "   • Create new access key"
echo "   • Run: aws configure"
echo ""
echo "Your Dockerfile is ready for either deployment method!"
