AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  CentralDeliveryHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "Authorization"
          - "Content-Type"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
      StageName: Prod

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fastapi-template/
      PackageType: Zip
      Handler: lambda_function.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DATABASE_URL: "sqlite:///delivery_platform.db"
          SECRET_KEY: production-secret-key-2025
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CentralDeliveryHttpApi
            Path: /{proxy+}
            Method: ANY

  ConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CentralizedDeliveryPlatform-Connections
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  HttpApiUrl:
    Description: "Production HTTP API endpoint"
    Value: !Sub "https://${CentralDeliveryHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
