AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        DisableGlobalScript: true
    Properties:
      CodeUri: fastapi-template/
      Architectures: [x86_64]
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
      Handler: lambda_function.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          DATABASE_URL: sqlite:///delivery_platform.db
          SECRET_KEY: production-secret-key-2025
      Events:
        ProxyHttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  # DynamoDB table for WebSocket connections
  ConnectionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: pk
        Type: String

  # WebSocket Lambda functions
  ConnectionManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fastapi-template/
      Handler: websocket.connect_disconnect.handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          CONN_TABLE: !Ref ConnectionTable
          WS_ENDPOINT: "wss://36jblgxwki.execute-api.us-east-1.amazonaws.com/production"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionTable

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fastapi-template/
      Handler: websocket.notification.handler
      Runtime: python3.11
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          CONN_TABLE: !Ref ConnectionTable
          WS_ENDPOINT: "wss://36jblgxwki.execute-api.us-east-1.amazonaws.com/production"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionTable
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: "arn:aws:execute-api:us-east-1:*:36jblgxwki/production/POST/@connections/*"

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub 'https://${FastApiFunctionHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
  
  WebSocketUrl:
    Description: WebSocket API endpoint URL (manually created)
    Value: "wss://36jblgxwki.execute-api.us-east-1.amazonaws.com/production"

  ConnectionTableName:
    Description: DynamoDB table for WebSocket connections
    Value: !Ref ConnectionTable
