/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:adc1f25d-92de-4cc8-a013-f0cdfdafeace",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9IItcBz7P",    // updated with real DeliveryPlatformUsers pool ID
    "aws_user_pools_web_client_id": "5r4pff0krdrblr5nkcfuglo4j1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "wizzadminpanel-20250721015606-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1ihimsuwuyezz.cloudfront.net"
};


export default awsmobile;
